[package]
name = "merkle-tree"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

